### ISSUE TITLE
Login Timer Expired.

### ISSUE THREAD

**Issue by HotFireyDeath** [Falkirks/Specter#10]
![snap1431568637526](https://cloud.githubusercontent.com/assets/11811152/7624717/312fd6b4-f9bb-11e4-9bd2-6307f0419636.jpg)
Note the image and how it says "Test logged out due to Kicked by admin. Reason: Login Timer Expired."

Now, is this supposed to be in Specter? I believe not.
Is this a bug, or is there another plugin that could be interfering with this one?

**Comment by PEMapModder** [comment]
`Login timer expired!` is not any string from Specter of PocketMine. It should be another plugin doing that. Maybe it is your custom auth plugin, that you need to login the secter to make it run?

**Comment by HotFireyDeath** [comment]
I now believe that it is @aliuly 's SimpleAuthHelper checking for AFK like users.
