### ISSUE TITLE
Bug 1.17.30

### ISSUE THREAD

**Issue by ItzStarlxy** [Falkirks/Specter#106]
ErrorException: "Undefined array key "SkinGeometryDataEngineVersion"" (EXCEPTION) in "pmsrc/src/pocketmine/Player" at line 1979

Error when i tried to spawn a specter

**Comment by DRAGKILLS** [comment]
I updated it to 1.17.30 u can see the pull requests
but not accepted

**Comment by inxomnyaa** [comment]
#105 #104
