### ISSUE TITLE
Invalid Skin

### ISSUE THREAD

**Issue by TheEpicCooldeal** [Falkirks/Specter#11]
I use /specter spawn YourMCHelper it tells me "YourMCHelper logged out due to invalid skin!"

Can you fix this?

**Comment by PEMapModder** [comment]
Issue already fixed in development build.

**Comment by TheEpicCooldeal** [comment]
Where can I download it?

**Comment by PEMapModder** [comment]
A .phar release will be available when other bugs have been fixed.

**Comment by TheEpicCooldeal** [comment]
Ok Thanks
