### ISSUE TITLE
0.11.x have BUG

### ISSUE THREAD

**Issue by kevin200** [Falkirks/Specter#12]
I can't send command from the dummy in 0.11.x

**Comment by legoboy0215** [comment]
pocketmine\network\protocol\MessagePacket
Does not exist now in PM 1.5

**Comment by PEMapModder** [comment]
I think we already deleted that code...

**Comment by PEMapModder** [comment]
The fix is in the PEMapModder-patch-1 branch.

**Comment by legoboy0215** [comment]
Yay!!! Fixed! Thanks to everyone!
