### ISSUE TITLE
Fatal Error: Call to function toBinary();

### ISSUE THREAD

**Issue by HotFireyDeath** [Falkirks/Specter#25]
An error occurs when I attempt to spawn a Specter. Happens on Mac and Ubuntu, I believe this doesn't happen on Windows.
![screenshot 2015-12-17 at 2 46 28 pm](https://cloud.githubusercontent.com/assets/11811152/11880093/ff8a5de2-a4cc-11e5-91e1-14cd9846245b.png)

Crash log is available : https://www.dropbox.com/s/bhcx4wc9ue8ezwc/CrashDump_Thu_Dec_17-19.41.31-UTC_2015.log?dl=0

**Comment by PEMapModder** [comment]
Why can't you link to a pastebin directly >.<

**Comment by HotFireyDeath** [comment]
I dislike pastebin. It's my personal preference.

**Comment by PEMapModder** [comment]
Well, it is kind of inconvenient to have to download another file just to view a text.

**Comment by PEMapModder** [comment]
No longer happens?

**Comment by HotFireyDeath** [comment]
Yeah, basically. I just tried the latest zip file instead of the releases tab...

**Comment by Falkirks** [comment]
@HotFireyDeath The latest release is rather behind the current development state. If the project is stable on the current MCPE and PocketMine version I will promote a new version, but things keep breaking rather constantly.
