### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by MorpheusTP** [Falkirks/Specter#39]
The Server is crash if /s s Player excuted.

**Comment by Falkirks** [comment]
Can you provide additional information? Is an error generated?

**Comment by MorpheusTP** [comment]
It doesn't generate one. It just crash my server

**Comment by Chris-Prime** [comment]
Plugin works fine!

**Comment by MorpheusTP** [comment]
Nope

**Comment by MorpheusTP** [comment]
@Falkirks
Here the CrashDump
Genisys Crash Dump Tue Dec 20 23:30:11 UTC 2016

Error: Call to undefined method pocketmine\Server::getUpdater()
File: /Specter-master/src/specter/network/SpecterPlayer
Line: 59
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN : Specter v0.4

Code:
[50]             $this->inventory->sendArmorContents($this);
[51] 
[52]             $this->server->getPluginManager()->callEvent($ev = new PlayerJoinEvent($this, TextFormat::YELLOW . $this->getName() . " joined the game"));
[53]             if(strlen(trim($ev->getJoinMessage())) > 0){
[54]                 $this->server->broadcastMessage($ev->getJoinMessage());
[55]             }
[56] 
[57]             $this->spawnToAll();
[58] 
[59]             if($this->server->getUpdater()->hasUpdate() and $this->hasPermission(Server::BROADCAST_CHANNEL_ADMINISTRATIVE)){
[60]                 $this->server->getUpdater()->showPlayerUpdate($this);
[61]             }
[62]         }
[63]     }
[64] }
[65] 
[66] 
[67] 
[68] 
[69] 

Backtrace:
#0 /src/pocketmine/Server(2774): pocketmine\Player->checkNetwork(boolean)
#1 /src/pocketmine/Server(2466): pocketmine\Server->tick(boolean)
#2 /src/pocketmine/Server(2344): pocketmine\Server->tickProcessor(boolean)
#3 /src/pocketmine/Server(1934): pocketmine\Server->start(boolean)
#4 /src/pocketmine/PocketMine(476): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/minecraft/multicraft/jar/genisys.phar/, string /home/minecraft/multicraft/servers/server688/, string /home/minecraft/multicraft/servers/server688/plugins/, string unknown)
#5 (1): require_once(string phar:///home/minecraft/multicraft/jar/genisys.phar/src/pocketmine/PocketMine.php)

Genisys version: c864589933da0468f2ab29a0c218a134a94a695a [Protocol 91; API 2.1.0]
uname -a: Linux mc5.hk-hosting.de 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 43 minutes 57 seconds
Number of loaded worlds: 2
Players online: 2/75

Loaded plugins:
Core 0.3.7 by morpheusTP for API(s) 2.0.0
Specter 0.4 by Falkirks for API(s) 1.13.0, 2.0.0

**Comment by Falkirks** [comment]
**Genisys** and other forks are not supported in any of my projects. Please do not submit further issues that exist in forks, but not in the main branch.
