### ISSUE TITLE
Specters not respawning

### ISSUE THREAD

**Issue by PEMapModder** [Falkirks/Specter#4]
After `2` being killed by `1`, (and should respawn, I did not apply the respawn config patch), `s c 1 chat` works normally but `s c 2 chat` doesn't. It just says `Sent packet` but nothing else is done.
It might be a problem related to my pulgin, although unlikely. Feel free to close if it is my problem.

**Comment by iJoshuaHD** [comment]
i dont have this issue even the specter player died many times.

**Comment by Falkirks** [comment]
Are you using v0.1 or the current source? I believe this issue was introduced after v1.0

**Comment by iJoshuaHD** [comment]
im using the latest from here.

**Comment by Falkirks** [comment]
@iJoshuaHD I will have to do some testing then

**Comment by PEMapModder** [comment]
@Falkirks this is the MessagePacket PR build.

**Comment by Falkirks** [comment]
@PEMapModder That is what I thought, I didn't see any issues in 0.1

**Comment by PEMapModder** [comment]
I don't seem to reproduce this anymore. Possibly my plugin's own fault.

**Comment by iJoshuaHD** [comment]
just confirmed this again. specter player is invisible after it dies. i had to reconnect again.

**Comment by Falkirks** [comment]
Do you have autorespawn on?

**Comment by iJoshuaHD** [comment]
oh theres an option? i didnt knew xD
