### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by CortexPE** [Falkirks/Specter#40]
I just did `s add test` on the console and the server crashed.

Heres my Crashdump:
`Genisys Crash Dump Tue Dec 27 08:12:28 CET 2016`

`Error: Call to undefined method pocketmine\Server::getUpdater()`
`File: /plugins/Specter-master/src/specter/network/SpecterPlayer`
`Line: 59`
`Type: notice`

`THIS CRASH WAS CAUSED BY A PLUGIN`
`BAD PLUGIN : Specter v0.4`

`Code:`
`[50]             $this->inventory->sendArmorContents($this);`
`[51] `
`[52]             $this->server->getPluginManager()->callEvent($ev = new PlayerJoinEvent($this, TextFormat::YELLOW . $this->getName() . " joined the game"));`
`[53]             if(strlen(trim($ev->getJoinMessage())) > 0){`
`[54]                 $this->server->broadcastMessage($ev->getJoinMessage());`
`[55]             }`
`[56] `
`[57]             $this->spawnToAll();`
`[58] `
`[59]             if($this->server->getUpdater()->hasUpdate() and $this->hasPermission(Server::BROADCAST_CHANNEL_ADMINISTRATIVE)){`
`[60]                 $this->server->getUpdater()->showPlayerUpdate($this);`
`[61]             }`
`[62]         }`
`[63]     }`
`[64] }`
`[65] `
`[66] `
`[67] `
`[68] `
`[69] `

`Backtrace:`
`#0 /src/pocketmine/Server(2774): pocketmine\Player->checkNetwork(boolean)`
`#1 /src/pocketmine/Server(2466): pocketmine\Server->tick(boolean)`
`#2 /src/pocketmine/Server(2344): pocketmine\Server->tickProcessor(boolean)`
`#3 /src/pocketmine/Server(1934): pocketmine\Server->start(boolean)`
`#4 /src/pocketmine/PocketMine(476): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /media/cortexpe/UbuntuHDD/TridentUHCs/, string /media/cortexpe/UbuntuHDD/TridentUHCs/, string /media/cortexpe/UbuntuHDD/TridentUHCs/plugins/, string unknown)`

`Genisys version: 0000000000000000000000000000000000000000 [Protocol 91; API 2.1.0]`
`uname -a: Linux MainServer 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64`
`PHP version: 7.0.2`
`Zend version: 3.0.0`
`OS : Linux, linux`

`Server uptime: 1 minutes 1 seconds`
`Number of loaded worlds: 1`
`Players online: 1/60`

`Loaded plugins:`
`DevTools 1.1-iTX by PocketMine Team & iTX Technologies LLC for API(s) 2.0.0`
`TridentUHC 3.9.2 by CortexPE for API(s) 1.1.0, 2.0.0`
`Specter 0.4 by Falkirks for API(s) 1.13.0, 2.0.0`

**Comment by Falkirks** [comment]
This plugin is created specifically for PocketMine and will not work with forks.
