### ISSUE TITLE
Genisys Support

### ISSUE THREAD

**Issue by ChaostixZix** [Falkirks/Specter#44]
Hi, I Need Help Here

I Realise That Genisys protocol Directory Is Not Inside The /src/network/mcpe , But Inside /src/network/

On Genysis, There's No handle() Function 
https://github.com/GenisysPro/GenisysPro/blob/539133a6cd1dcd034a564fdc6fc27503341a9bf6/src/pocketmine/network/protocol/LoginPacket.php

Can You Help Me With This?

**Comment by Thunder33345** [comment]
To quote falk
"This plugin is created specifically for PocketMine and will not work with forks."

**Comment by Falkirks** [comment]
Adding to @Thunder33345, this a PocketMine debugging tool, it helps you diagnose errors in plugins. None of my plugins support non PM servers, but this one specifically won't as it latches itself onto the lower level API to add players through its own network interface. If you are looking for a replacement for Specter on Genisys, make your own.

**Comment by PEMapModder** [comment]
Older versions won't work well either, since they use Server::getUpdater() anyway
