### ISSUE TITLE
An unknow error occured while attempting command :-

### ISSUE THREAD

**Issue by optimusprime338** [Falkirks/Specter#49]
console error:-
18.06 02:51:47 [Server] Server thread/CRITICAL ErrorException: "zlib_decode(): data error" (EXCEPTION) in "/Specter .phar/src/specter/network/SpecterInterface" at line 118
18.06 02:51:47 [Server] Server thread/CRITICAL Unhandled exception executing command 'specter spawn villager' in specter: zlib_decode(): data error
18.06 02:51:47 [Server] Server thread/NOTICE Player data not found for "villager", creating new profile

**Comment by SOF3** [comment]
Are you using the latest version?

Also **note that Specter is not for spawning NPCs. Keep in mind that if you just want a villager, use [Slapper](https://poggit.pmmp.io/p/Slapper) instead.**

**Comment by optimusprime338** [comment]
No I just wanted to name "villager" and yes I m using latest commit

**Comment by SOF3** [comment]
The bug should have been fixed today in #48 :thinking:

**Comment by optimusprime338** [comment]
May it's my side problem then

**Comment by CortexPE** [comment]
Same error for me :/
![image](https://user-images.githubusercontent.com/17762324/27433456-6d8d966e-571a-11e7-9752-353ea676ad87.png)

**Comment by optimusprime338** [comment]
I still can't​ use this plugin
