### ISSUE TITLE
auth problem!

### ISSUE THREAD

**Issue by optimusprime338** [Falkirks/Specter#52]
authenticator kicking dummy :- 
30.06 16:36:53 [Server] Server thread/INFO new[/SPECTER:19133] logged out due to Kicked by admin. Reason: Login Timeout

**Comment by SOF3** [comment]
Because this is what specter is for...

**Comment by SOF3** [comment]
Because this is what Specter is for... Specter is a plugin for testing plugins. Why do you want an auth plugin on a test server?

**Comment by Falkirks** [comment]
@SOF3 is correct. This is not an issue.
