### ISSUE TITLE
Plugin won't load.

### ISSUE THREAD

**Issue by HittmanA** [Falkirks/Specter#54]
I get this error every time I try to start my server with specter:
```
Fatal error: Declaration of specter\network\SpecterInterface::setName($name) must be compatible with pocketmine\network\SourceInterface::setName(string $name) in /home/hittmana/Pocketmine/plugins/Specter-master 2/src/specter/network/SpecterInterface.php on line 24
```

**Comment by dktapps** [comment]
Checkout tag `1.6.2dev-3.0.0-ALPHA6` or use the last promoted Alpha build from Jenkins. Latest master has extensive changes which haven't yet been documented in a release.
