### ISSUE TITLE
ICU

### ISSUE THREAD

**Issue by LagHD** [Falkirks/Specter#65]
Would it be possible, to control the fake player created without having to use the IControlU plugin, bc that plugin is outdated, yes even with my all api loader that plugin won't work, some lines of code of inventory, player death animation, and etc

**Comment by Falkirks** [comment]
You can move it to specific coordinates with `/s m`

**Comment by LagHD** [comment]
Ye ik, just would've been cool to control it still lol

**Comment by SOF3** [comment]
then why aren't you requesting to update ICU rather than updating Specter?
