### ISSUE TITLE
Respawn is not working

### ISSUE THREAD

**Issue by SOF3** [falkirks/Specter#75]
The specter is still unable to chat despite typing `s respawn <player>`. `s q` + `s s`, on the other hand, seems to respawn the specter.

**Comment by Falkirks** [comment]
Is this a new thing on later versions? I haven't tested respawn for a while.

**Comment by thebigsmileXD** [comment]
Fixed in https://github.com/falkirks/Specter/commit/10c118e64d2a1e9b86be1a2969cdf04e318127d0
