### ISSUE TITLE
Plugin crashes on use of chat subcommand

### ISSUE THREAD

**Issue by Zedstar16** [falkirks/Specter#77]
It'd be great if this could be fixed asap as Specter is such a useful plugin for Plugin Development :)
-Whenever i try to use the chat subcommand in Specter, /s c the plugin crashes with the error:

Error: Cannot write non-existing field "source"
File: src/pocketmine/network/mcpe/protocol/DataPacket
Line: 146
Type: Error

Code:
[137] 
[138] 		return $data;
[139] 	}
[140] 
[141] 	public function __get($name){
[142] 		throw new \Error("Cannot read non-existing field \"$name\"");
[143] 	}
[144] 
[145] 	public function __set($name, $value){
[146] 		throw new \Error("Cannot write non-existing field \"$name\"");
[147] 	}
[148] }

Backtrace:
#0 Specter_dev-26.phar/src/specter/Specter(144): pocketmine\network\mcpe\protocol\DataPacket->__set(string source, string )
#1 src/pocketmine/command/PluginCommand(58): specter\Specter->onCommand(pocketmine\command\ConsoleCommandSender object, pocketmine\command\PluginCommand object, string s, array Array())
#2 src/pocketmine/command/SimpleCommandMap(256): pocketmine\command\PluginCommand->execute(pocketmine\command\ConsoleCommandSender object, string s, array Array())
#3 src/pocketmine/Server(1960): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\command\ConsoleCommandSender object, string s c test hi)
#4 src/pocketmine/Server(1547): pocketmine\Server->dispatchCommand(pocketmine\command\ConsoleCommandSender object, string s c test hi)
#5 vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\Server->pocketmine\{closure}()
#6 vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#7 src/pocketmine/Server(2278): pocketmine\snooze\SleeperHandler->sleepUntil(double 1544732125.0642)
#8 src/pocketmine/Server(2139): pocketmine\Server->tickProcessor()
#9 src/pocketmine/Server(1715): pocketmine\Server->start()
#10 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\ZZach\Documents\00Plugin Development\PMMP Server\PocketMine-MP PluginDevelopment\, string C:\Users\ZZach\Documents\00Plugin Development\PMMP Server\PocketMine-MP PluginDevelopment\plugins\)
#11 C:/Users/ZZach/Documents/00Plugin Development/PMMP Server/PocketMine-MP PluginDevelopment/PocketMine-MP.phar(1): require(string phar://C:/Users/ZZach/Documents/00Plugin Development/PMMP Server/PocketMine-MP PluginDevelopment/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.5.0 [Protocol 313]
Git commit: 2323601f98bf5f48901cd57b96d0e680a7d5e56e
uname -a: Windows NT ZACHS-PC 10.0 build 17134 (Windows 10) AMD64
PHP Version: 7.2.6
Zend version: 3.2.0
OS : WINNT, win

Loaded plugins:
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
ManyWorlds 2.2.0 by aliuly for API(s) 3.0.0
DevTools 1.13.0 by PocketMine Team for API(s) 3.0.0
PurePerms 1.4.2 by 64FF00 & ProjectInfinity for API(s) 3.0.0
Specter 0.5 by Falkirks for API(s) 3.0.0, 4.0.0
8ball 0.0.1 by Zedstar16 for API(s) 3.3.0
ClientConsole 0.1.0 by dktapps for API(s) 3.0.0
PvPSystem by Zedstar16 for API(s) 3.3.0
NoDupe 0.0.1 by Zedstar16 for API(s) 3.3.0
NoVoidPlus 0.0.1 by Zedstar16 for API(s) 3.0.0
SimpleGamemode 0.1 by Zedstar16 for API(s) 3.0.0

**Comment by KielKing** [comment]
https://github.com/falkirks/Specter/pull/80
