### ISSUE TITLE
Ban

### ISSUE THREAD

**Issue by DaRealPandaz** [falkirks/Specter#82]
if u ban player and try to spawn him back u et ISE

**Comment by artulloss** [comment]
That's about the least helpful issue you can make- please link the console output of the internal server error.

**Comment by thebigsmileXD** [comment]
Can you please provide more information?

**Comment by thebigsmileXD** [comment]
Probably a crash that was caused when doing `/s s name` when a player is banned or the server is whitelisted. Fixed in https://github.com/falkirks/Specter/commit/43ee5232601820f683204344c0ab6e7e59f73e78
