### ISSUE TITLE
Undefined Index: AnimatedImageData

### ISSUE THREAD

**Issue by Unickorn** [falkirks/Specter#84]
I couldn't spawn a specter on version 3.11.1.

[Tue_Dec_24-20.52.39-EAT_2019.log](https://github.com/falkirks/Specter/files/3998835/Tue_Dec_24-20.52.39-EAT_2019.log)

**Comment by thebigsmileXD** [comment]
Fixed by https://github.com/falkirks/Specter/commit/80f7f0575cda912f633fc340ba19b84037e96154
