### ISSUE TITLE
sign and slapper interactions

### ISSUE THREAD

**Issue by mote166** [falkirks/Specter#87]
this is just as issue #37 states but with more information and a feature request which might solve this issue.

**issue:** when you use icu and try to touch a sign which should teleport you makes you join a game or says something for you (ex: /sudo) the touch is considered by you and not the specter, same goes for slappers.

**feature request**: idk if its possible but if it is, add a command that makes the specter touch whatever is in front of him, like we move it to face the sign or the slapper and then we do for example "/s interact 'specter name' " and it touches the sign or the slapper in front of it.

although this might be an issue with icu itself but i haven't tested that yet.

**Comment by thebigsmileXD** [comment]
Could've added a comment. Closing as duplicate.
