### ISSUE TITLE
Cannot remove Specter + cannot hurt?

### ISSUE THREAD

**Issue by HotFireyDeath** [Falkirks/Specter#9]
Hi! When I use Specter to test my plugins, it seems I cannot hurt the generated player! Now, my plugin kind of depended on hurting players. Is that a bug or are there a feature to do so?

Also, I cannot seem to remove my Specter, even through server disconnection. This is an issue because I don't want useless, empty players on my server standing there.

So, are these issues? Or is there a fix?

**Comment by Falkirks** [comment]
Are you using 1.5 and 0.11? If so, there isn't any support yet.

**Comment by HotFireyDeath** [comment]
No, I was using the 1.4.1 version of PocketMine...

**Comment by PEMapModder** [comment]
/kick doesn't work and /s q doesn't work either?

For hurting, if a normal player spawned there, can he be hurt?

**Comment by HotFireyDeath** [comment]
No, @PEMapModder , normal players can be hurt, but Specters can't.
I didn't try the /kick or /s q yet :)

**Comment by HotFireyDeath** [comment]
When I log out, logging back in, the Specter comes back.

**Comment by PEMapModder** [comment]
@HotFireyDeath you need to authenticate your specter to SimpleAuth, or some other plugins blocked the specter from being damaged.

Specters work as normal players. They are basically handled the same as normal players except that there isn't a remote device connecting for it. So it's normal that the Specter remains there right?

If you don't use /s q or /kick to disconnect the player, what do you use?

Do you even know what Specter is about?

**Comment by HotFireyDeath** [comment]
@PEMapModder that is why I created the thread, because I cannot remove them from the world. Also, I use Specter for testing purpose, like testing plugins that require player i/o. This cannot be achieved because the Specters seem to not be hurt at all.

**Comment by PEMapModder** [comment]
@HotFireyDeath it appears that another plugin is cancelllinf the event. Did you read the console about the messages sent to the specter?

**Comment by HotFireyDeath** [comment]
I cannot kill them manually as I can kill a regular player. They cannot be hurt in any manner, even through the void. @PEMapModder  is it supposed to be that they automatically rejoin after you close and open the server?

**Comment by PEMapModder** [comment]
No they wouldn't auto rejoin if the server is *restarted*.

About not being able to get hurt, can you create an event listener with `@ignoreCancelled ` set to false at MONITOR priority and see if the event is ever fired when it is attacked, and whether it is cancelled

**Comment by HotFireyDeath** [comment]
Yes, I will try that very soon.
