### ISSUE TITLE
error when joining a specter with pmmp 1.14.60

### ISSUE THREAD

**Issue by mote166** [falkirks/Specter#90]
```[17:38:05] [Server thread/CRITICAL]: ErrorException: "Undefined index: PersonaPieces" (EXCEPTION) in "src/pocketmine/Player" at line 1865```

**Comment by thebigsmileXD** [comment]
🙄 #89 #88

**Comment by thebigsmileXD** [comment]
I wonder if we should add the `mcpe-protocol` entry in the `plugin.yml` to stop this from happening, but then we must update the plugin with every mcpe version.

**Comment by SOF3** [comment]
@thebigsmileXD You should really do that.

**Comment by thebigsmileXD** [comment]
@SOF3 but it would kind of suppress the errors (they wont happen at all), which means more work for me figuring out why a newer version does not function.
I do not have instant access to the latest mcpe versions when they release. Actually right now i am still on 1.14.20

**Comment by thebigsmileXD** [comment]
> mcpe-protocol

is added, support for new version was added in #89
