### ISSUE TITLE
cant spawn specter

### ISSUE THREAD

**Issue by owenraihan** [falkirks/Specter#91]
I cant spawn a specter it said failed to open session

**Comment by SOF3** [comment]
Anything else it says?

**Comment by owenraihan** [comment]
So turns out my server was whitelisted so it worked, but when I tried to
icu the specter it crashes me, I used latest dev icu plugin.

**Comment by thebigsmileXD** [comment]
Closing as invalid. Head to ICU repo for ICU bugs.
