### ISSUE TITLE
invalid skin

### ISSUE THREAD

**Issue by mote166** [falkirks/Specter#92]
specter can't join a server running pmmp 3.14.0, it gets kicked with the reason "kicked due to invalid skin "

**Comment by thebigsmileXD** [comment]
There have been no API changes in 3.14.0 that affect skins. This plugin has a protocol version - it will not load on other versions than 3.11
https://github.com/falkirks/Specter/blob/55345188cbfc3a31e54d9e65b1bce4cd584e939c/plugin.yml#L6
Thus closing as invalid.
