### ISSUE TITLE
Erreur when try to /specter spawn [PlayerName]

### ISSUE THREAD

**Issue by AyzrixYTB** [falkirks/Specter#96]
PocketMine-MP Crash Dump Wed Sep 30 13:09:24 CEST 2020

Error: Not enough bytes left in buffer: need 1, have 0
File: vendor/pocketmine/binaryutils/src/BinaryStream
Line: 103
Type: pocketmine\utils\BinaryDataException

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: Specter v0.9

Code:
[94] 			$this->offset = $buflen;
[95] 			return $str;
[96] 		}
[97] 		if($len < 0){
[98] 			$this->offset = $buflen - 1;
[99] 			return "";
[100] 		}
[101] 		$remaining = $buflen - $this->offset;
[102] 		if($remaining < $len){
[103] 			throw new BinaryDataException("Not enough bytes left in buffer: need $len, have $remaining");
[104] 		}
[105] 
[106] 		return $len === 1 ? $this->buffer[$this->offset++] : substr($this->buffer, ($this->offset += $len) - $len, $len);
[107] 	}
[108] 
[109] 	/**
[110] 	 * @return string
[111] 	 * @throws BinaryDataException
[112] 	 */
[113] 	public function getRemaining() : string{

Backtrace:
#0 src/pocketmine/network/mcpe/protocol/BatchPacket(54): pocketmine\utils\BinaryStream->get(integer 1)
#1 src/pocketmine/network/mcpe/protocol/DataPacket(91): pocketmine\network\mcpe\protocol\BatchPacket->decodeHeader()
#2 plugins/Specter-master/src/specter/network/SpecterInterface(143): pocketmine\network\mcpe\protocol\DataPacket->decode()
#3 src/pocketmine/Player(3298): specter\network\SpecterInterface->putPacket(object specter\network\SpecterPlayer, object pocketmine\network\mcpe\protocol\BatchPacket, boolean , boolean )
#4 plugins/NitroFactions/src/Nitro/API/ScoreAPI(122): pocketmine\Player->sendDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
#5 plugins/NitroFactions/src/Nitro/API/ScoreAPI(170): Nitro\API\ScoreAPI->set()
#6 plugins/NitroFactions/src/Nitro/Events/PlayerJoin(65): Nitro\API\ScoreAPI::createFactionLines(object specter\network\SpecterPlayer)
#7 src/pocketmine/plugin/MethodEventExecutor(42): Nitro\Events\PlayerJoin->PlayerJoin(object pocketmine\event\player\PlayerJoinEvent)
#8 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object Nitro\Events\PlayerJoin, object pocketmine\event\player\PlayerJoinEvent)
#9 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\player\PlayerJoinEvent)
#10 src/pocketmine/Player(1086): pocketmine\event\Event->call()
#11 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(315): pocketmine\Player->doFirstSpawn()
#12 src/pocketmine/network/mcpe/protocol/SetLocalPlayerAsInitializedPacket(45): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleSetLocalPlayerAsInitialized(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket)
#13 plugins/Specter-master/src/specter/network/SpecterInterface(303): pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
#14 plugins/Specter-master/src/specter/network/SpecterInterface(241): specter\network\SpecterInterface->sendPacket(object specter\network\SpecterPlayer, object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket)
#15 plugins/Specter-master/src/specter/Specter(54): specter\network\SpecterInterface->openSession(string[6] Ayzrix, string[7] SPECTER, integer 19133)
#16 src/pocketmine/command/PluginCommand(54): specter\Specter->onCommand(object pocketmine\command\ConsoleCommandSender, object pocketmine\command\PluginCommand, string[1] s, array[2])
#17 src/pocketmine/command/SimpleCommandMap(248): pocketmine\command\PluginCommand->execute(object pocketmine\command\ConsoleCommandSender, string[1] s, array[2])
#18 src/pocketmine/Server(1811): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\command\ConsoleCommandSender, string[14] s spawn Ayzrix)
#19 src/pocketmine/Server(1423): pocketmine\Server->dispatchCommand(object pocketmine\command\ConsoleCommandSender, string[14] s spawn Ayzrix)
#20 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\Server->pocketmine\{closure}()
#21 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
#22 src/pocketmine/Server(2157): pocketmine\snooze\SleeperHandler->sleepUntil(double 1601464164.5464)
#23 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()
#24 src/pocketmine/Server(1588): pocketmine\Server->start()
#25 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[22] /home/debian/Faction1/, string[30] /home/debian/Faction1/plugins/)
#26 src/pocketmine/PocketMine(304): pocketmine\server()
#27 (11): require(string[77] phar:///home/debian/Faction1/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.15.0 [Protocol 408]
Git commit: a498b0415ab2edf18300470dfe6d182372f25190
uname -a: Linux ns3027161 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64
PHP Version: 7.3.14
Zend version: 3.3.14
OS : Linux, linux

**Comment by SOF3** [comment]
Which version of Specter are you using?

**Comment by HydroGames-dev** [comment]
Hey

``
#2 plugins/Specter-master/src/specter/network/SpecterInterface(143): pocketmine\network\mcpe\protocol\DataPacket->decode()
#3 src/pocketmine/Player(3298): specter\network\SpecterInterface->putPacket(object specter\network\SpecterPlayer, object pocketmine\network\mcpe\protocol\BatchPacket, boolean , boolean )
#4 plugins/NitroFactions/src/Nitro/API/ScoreAPI(122): pocketmine\Player->sendDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
#5 plugins/NitroFactions/src/Nitro/API/ScoreAPI(170): Nitro\API\ScoreAPI->set()
#6 plugins/NitroFactions/src/Nitro/Events/PlayerJoin(65): Nitro\API\ScoreAPI::createFactionLines(object specter\network\SpecterPlayer)
#7 src/pocketmine/plugin/MethodEventExecutor(42): Nitro\Events\PlayerJoin->PlayerJoin(object pocketmine\event\player\PlayerJoinEvent)``

It's not Specter plugin it's nitrofaction plugin

**Comment by thebigsmileXD** [comment]
> 
> 
> Which version of Specter are you using?

>  BAD PLUGIN: Specter v0.9

**Comment by SOF3** [comment]
> > @SOF3
> > Which version of Specter are you using?
> 
> > BAD PLUGIN: Specter v0.9

yeah but there have been several commits since we set version to 0.9
